### PR TITLE
Dev/113 fix log class endpoint received

### LINKED ISSUE #113: Fix Log class endpoint received
Currently the `Received GET` log, it Logs at an `Application` level

### PR DESCRIPTION
**Pull request by ruuffian**
Closes #113 #115 #111 #108 #101 #86

### CODE REVIEW

**Comment by ruuffian** [comment]
Next steps are to add logging in service classes, implement event group functionality, and remove in-memory repos.

**Comment by ruuffian** [comment]
For my own sanity, I'm removing #108 from this. Ready for review.

File: src/main/kotlin/com/lowbudgetlcs/api/routes/v1/player/PlayerEndpointsV1.kt [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+import io.ktor.server.request.*
+import io.ktor.server.resources.*
+import io.ktor.server.resources.patch
+import io.ktor.server.resources.post
+import io.ktor.server.response.*
+import io.ktor.server.routing.*
+import org.slf4j.Logger
+import org.slf4j.LoggerFactory
+
+private val logger: Logger = LoggerFactory.getLogger(Application::class.java)
```
Comment (zainaraza43) [inline src/main/kotlin/com/lowbudgetlcs/api/routes/v1/player/PlayerEndpointsV1.kt:19]: WHAT IS WITH THE `APPLICATION::CLASS.JAVA` WHAT IS HAPPENING?
AND WHY IS GITHUB SAYING THIS IS A NEW CLASS?

File: src/main/kotlin/com/lowbudgetlcs/api/routes/v1/team/TeamEndpointsV1.kt [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+import io.ktor.server.request.*
+import io.ktor.server.resources.*
+import io.ktor.server.resources.post
+import io.ktor.server.response.*
+import io.ktor.server.routing.*
+import org.slf4j.Logger
+import org.slf4j.LoggerFactory
+
+
+private val logger: Logger = LoggerFactory.getLogger(Application::class.java)
```
Comment (zainaraza43) [inline src/main/kotlin/com/lowbudgetlcs/api/routes/v1/team/TeamEndpointsV1.kt:20]: AGAIN IM SO CONFUSED

File: src/main/kotlin/com/lowbudgetlcs/domain/services/event/EventService.kt [hunk 3]
```diff
@@ -1,94 +1,117 @@
...
+import org.slf4j.Logger
+import org.slf4j.LoggerFactory
+
+class EventService(
+    private val eventRepo: IEventRepository,
+    private val tournamentGateway: IRiotTournamentGateway,
+    private val teamRepo: ITeamRepository,
+    private val seriesRepo: ISeriesRepository
+) : IEventService {
+    private val logger: Logger by lazy { LoggerFactory.getLogger(this::class.java) }
```
Comment (zainaraza43) [inline src/main/kotlin/com/lowbudgetlcs/domain/services/event/EventService.kt:20]: again what is with the different logging practices?

File: src/main/kotlin/com/lowbudgetlcs/domain/services/game/GameService.kt [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+        logger.debug("Fetching tournament id for event '${series.eventId}'...t add")
+        val tid = eventRepo.getById(series.eventId)?.riotTournamentId
+            ?: throw DatabaseException("Series found with no parent event.")
+        // fetch shortcode
+        val shortcode =
+            gate.getCode(tid, NewShortcode())?.codes?.first() ?: throw GatewayException("Failed to create shortcode.")
+        // insert data
+        return gameRepo.insert(newGame, shortcode.toShortcode(), series.id)
+            ?: throw DatabaseException("Failed to save game.")
+    }
```
Comment (zainaraza43) [inline src/main/kotlin/com/lowbudgetlcs/domain/services/game/GameService.kt:48]: this looks really nasty can we clean this up?

File: src/main/kotlin/com/lowbudgetlcs/domain/services/series/SeriesService.kt [hunk 5]
```diff
@@ -1,43 +1,56 @@
...
+import com.lowbudgetlcs.repositories.series.ISeriesRepository
+import com.lowbudgetlcs.repositories.team.ITeamRepository
+import org.slf4j.Logger
+import org.slf4j.LoggerFactory
+
+class SeriesService(
+    private val seriesRepository: ISeriesRepository, private val teamRepository: ITeamRepository
+) : ISeriesService {
+
+    private val logger: Logger by lazy { LoggerFactory.getLogger(this::class.java) }
```
Comment (zainaraza43) [inline src/main/kotlin/com/lowbudgetlcs/domain/services/series/SeriesService.kt:17]: again with the logger

File: src/main/kotlin/com/lowbudgetlcs/domain/services/team/TeamService.kt [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+import com.lowbudgetlcs.domain.models.team.*
+import com.lowbudgetlcs.repositories.DatabaseException
+import com.lowbudgetlcs.repositories.team.ITeamRepository
+import org.slf4j.Logger
+import org.slf4j.LoggerFactory
+
+class TeamService(
+    private val teamRepository: ITeamRepository
+) : ITeamService {
+    private val logger: Logger by lazy { LoggerFactory.getLogger(this::class.java) }
```
Comment (zainaraza43) [inline src/main/kotlin/com/lowbudgetlcs/domain/services/team/TeamService.kt:12]: again with the logger, I'd prefer if we stayed consistent

File: src/main/kotlin/com/lowbudgetlcs/domain/services/account/AccountService.kt [hunk 7]
```diff
@@ -0,0 +1,46 @@
...
+import com.lowbudgetlcs.gateways.riot.account.IRiotAccountGateway
+import com.lowbudgetlcs.repositories.DatabaseException
+import com.lowbudgetlcs.repositories.account.IAccountRepository
+import org.slf4j.Logger
+import org.slf4j.LoggerFactory
+
+class AccountService(
+    private val accountRepository: IAccountRepository, private val riotAccountGateway: IRiotAccountGateway
+) : IAccountService {
+    private val logger: Logger by lazy { LoggerFactory.getLogger(this::class.java) }
```
[the remark this answers is not in the document]
Comment (ruuffian) [reply src/main/kotlin/com/lowbudgetlcs/domain/services/account/AccountService.kt:16]: The logger is the same, it's just using a lazy initializer. If you have a strong preference between lazy vs not-lazy we can switch but I don't think it matters.

File: src/main/kotlin/com/lowbudgetlcs/api/routes/v1/event/EventEndpointsV1.kt [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+import io.ktor.server.request.*
+import io.ktor.server.resources.*
+import io.ktor.server.resources.patch
+import io.ktor.server.resources.post
+import io.ktor.server.response.*
+import io.ktor.server.routing.*
+import org.slf4j.Logger
+import org.slf4j.LoggerFactory
+
+private val logger: Logger = LoggerFactory.getLogger(Application::class.java)
```
[the remark this answers is not in the document]
Comment (ruuffian) [reply src/main/kotlin/com/lowbudgetlcs/api/routes/v1/event/EventEndpointsV1.kt:23]: Extension functions are registered outside of the class scope so there is no `this` inside any of these files.

File: src/main/kotlin/com/lowbudgetlcs/domain/services/game/GameService.kt (hunk 4 above)
Comment (zainaraza43) [reply src/main/kotlin/com/lowbudgetlcs/domain/services/game/GameService.kt]: you can break this out into more variables and utilize `(::function)`

File: src/main/kotlin/com/lowbudgetlcs/domain/services/account/AccountService.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (zainaraza43) [reply src/main/kotlin/com/lowbudgetlcs/domain/services/account/AccountService.kt:16]: not lazy is preferred if you can stick to it

File: src/main/kotlin/com/lowbudgetlcs/domain/services/game/GameService.kt (hunk 4 above)
Comment (ruuffian) [reply src/main/kotlin/com/lowbudgetlcs/domain/services/game/GameService.kt]: image

Is this better?

Comment (zainaraza43) [reply src/main/kotlin/com/lowbudgetlcs/domain/services/game/GameService.kt]: looks better :D

**Review by zainaraza43 — APPROVED** [review]
great job proud of you :3
